name: "Azure Subscription Deployment"
description: "Runs New-AzSubscriptionDeployment"

inputs:
  location:
    required: true
    default: "centralus"
  template_file:
    required: true
  parameter_file:
    required: false
  what_if:
    required: true
    default: "true"
runs:
  using: "composite"
  steps:
    - name: App Service Resource Group Deploy
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $params = @{
            WhatIf = "false" -ne "${{ inputs.what_if }}"
            Location = "${{ inputs.location }}"
            TemplateFile = "${{ inputs.template_file }}"
            TemplateParameterFile = "${{ inputs.parameter_file }}"
          }
          Write-Host "Running New-AzSubscriptionDeployment... $($params | Out-String)"
          New-AzSubscriptionDeployment @params
        azPSVersion: "latest"
        failOnStandardError: "true"
