name: "Cosmos Database CI / CD"

on:
  pull_request:
    paths:
      [
        infrastructure/repost-cosmos/**.bicep,
        infrastructure/repost-cosmos/**.parameters.json,
      ]
  push:
    branches: [main]
    paths:
      [
        infrastructure/repost-cosmos/**.bicep,
        infrastructure/repost-cosmos/**.parameters.json,
      ]
  workflow_dispatch:
    inputs:
      What-If:
        description: "What-If: Set to 'false' if you want to deploy"
        required: true
        default: "true"

env:
  cosmos_template: "infrastructure/repost-cosmos/cosmos.bicep"
  location: "eastus"
  resource_group_name: "repost-cosmos"
  resource_group_template: "infrastructure/repost-cosmos/resource-group.bicep"
  service_principal_id: "a815ac51-ea5e-4b31-aa3c-eefb9c87403b"
  service_principal_secret: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
  subcription_id: "59b7bd22-db8a-4752-840e-6b4507317ff0"
  tenant_id: "87e276c0-7d18-4d86-948a-ba5eea990211"

jobs:
  what-if-deploy:
    name: "What-If Cosmos Deploy"
    if: github.event_name == 'pull_request' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.What-If == 'true' )
    runs-on: ubuntu-latest
    environment:
      name: "production"
    env:
      what_if: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: ./.github/workflows/composite/azure-login
        with:
          service_principal_id: ${{ env.service_principal_id }}
          service_principal_secret: ${{ env.service_principal_secret }}
          subcription_id: ${{ env.subcription_id }}
          tenant_id: ${{ env.tenant_id }}
      - name: What-If Deploy Resource Group
        uses: ./.github/workflows/composite/azure-subscription-deployment
        with:
          location: ${{ env.location }}
          template_file: ${{ env.resource_group_template }}
          what_if: ${{ env.what_if }}
      - name: What-If Deploy Cosmos
        uses: ./.github/workflows/composite/azure-resourcegroup-deployment
        with:
          resource_group_name: ${{ env.resource_group_name }}
          template_file: ${{ env.cosmos_template }}
          what_if: ${{ env.what_if }}
  deploy:
    name: "Cosmos Deploy"
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.What-If == 'false' ))
    concurrency: cosmos-deploy
    runs-on: ubuntu-latest
    environment:
      name: "production"
    env:
      what_if: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: ./.github/workflows/composite/azure-login
        with:
          service_principal_id: ${{ env.service_principal_id }}
          service_principal_secret: ${{ env.service_principal_secret }}
          subcription_id: ${{ env.subcription_id }}
          tenant_id: ${{ env.tenant_id }}
      - name: Deploy Resource Group
        uses: ./.github/workflows/composite/azure-subscription-deployment
        with:
          location: ${{ env.location }}
          template_file: ${{ env.resource_group_template }}
          what_if: ${{ env.what_if }}
      - name: Deploy Cosmos
        uses: ./.github/workflows/composite/azure-resourcegroup-deployment
        with:
          resource_group_name: ${{ env.resource_group_name }}
          template_file: ${{ env.cosmos_template }}
          what_if: ${{ env.what_if }}
