name: "App Service CI / CD"

on:
  pull_request:
    paths: [infrastructure/repost-app/**]
  push:
    branches: [main]
    paths: [infrastructure/repost-app/**]
  workflow_dispatch:
    inputs:
      What-If:
        description: "What-If: Set to 'false' if you want to deploy"
        required: true
        default: "true"

env:
  service_principal_id: "a815ac51-ea5e-4b31-aa3c-eefb9c87403b"
  subcription_id: "59b7bd22-db8a-4752-840e-6b4507317ff0"
  tenant_id: "87e276c0-7d18-4d86-948a-ba5eea990211"
  location: "centralus"
  resource_group_name: "repost-app"
  resource_group_template: "infrastructure/repost-app/resource-group.bicep"
  app_service_template: "infrastructure/repost-app/app-service.bicep"
  # Secrets
  cosmos_primary_key_secret: ${{ secrets.COSMOS_PRIMARY_KEY }}
  github_app_client_secret: ${{ secrets.GITHUBAPP_CLIENT_SECRET }}
  github_app_private_ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
  github_app_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
  service_principal_secret: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}

jobs:
  what-if-deploy:
    name: "What-If App Service Deploy"
    runs-on: ubuntu-latest
    environment:
      name: "production"
    env:
      what_if: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: ./.github/workflows/composite/azure-login
        with:
          service_principal_id: ${{ env.service_principal_id }}
          service_principal_secret: ${{ env.service_principal_secret }}
          subcription_id: ${{ env.subcription_id }}
          tenant_id: ${{ env.tenant_id }}
      - name: What-If Deploy Resource Group
        uses: ./.github/workflows/composite/azure-subscription-deployment
        with:
          location: ${{ env.location }}
          template_file: ${{ env.resource_group_template }}
          what_if: ${{ env.what_if }}
      - name: What-If Deploy App Service
        uses: ./.github/workflows/composite/azure-resourcegroup-deployment
        with:
          resource_group_name: ${{ env.resource_group_name }}
          template_file: ${{ env.app_service_template }}
          what_if: ${{ env.what_if }}
  deploy:
    name: "App Service Deploy"
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || ( github.event_name == 'workflow_dispatch' && inputs.What-If == 'false' )) }}
    needs: [what-if-deploy]
    concurrency: app-service-deploy
    runs-on: ubuntu-latest
    environment:
      name: "production"
    env:
      what_if: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: ./.github/workflows/composite/azure-login
        with:
          service_principal_id: ${{ env.service_principal_id }}
          service_principal_secret: ${{ env.service_principal_secret }}
          subcription_id: ${{ env.subcription_id }}
          tenant_id: ${{ env.tenant_id }}
      - name: Deploy Resource Group
        uses: ./.github/workflows/composite/azure-subscription-deployment
        with:
          location: ${{ env.location }}
          template_file: ${{ env.resource_group_template }}
          what_if: ${{ env.what_if }}
      - name: Deploy App Service
        uses: ./.github/workflows/composite/azure-resourcegroup-deployment
        with:
          resource_group_name: ${{ env.resource_group_name }}
          template_file: ${{ env.app_service_template }}
          what_if: ${{ env.what_if }}
      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["infrastructure/repost-app/appSettings.json"]'
        env:
          COSMOS_PRIMARY_KEY: ${{ env.cosmos_primary_key_secret }}
          GITHUB_CLIENT_SECRET: ${{ env.github_app_client_secret }}
          PRIVATE_SSH_KEY: ${{ env.github_app_private_ssh_key }}
          WEBHOOK_SECRET: ${{ env.github_app_webhook_secret }}
      - name: Deploy App Settings
        uses: ./.github/workflows/composite/azure-appsettings-deployment
        with:
          settings: "@infrastructure/repost-app/appSettings.json"
