name: "Web App CI"

on:
  pull_request:
    paths: [web-app/src/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and test
        uses: ./.github/workflows/composite/web-app-build-test
