name: "Azure Resource Group Deployment"
description: "Runs New-AzResourceGroupDeployment"

inputs:
  deployment_name:
    required: false
  parameter_file:
    required: false
  resource_group_name:
    required: true
    default: "centralus"
  template_file:
    required: true
  what_if:
    required: true
    default: "true"
runs:
  using: "composite"
  steps:
    - name: App Service Resource Group Deploy
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $params = @{
            ResourceGroupName = "${{ inputs.resource_group_name }}"
            TemplateFile = "${{ inputs.template_file }}"
            WhatIf = "false" -ne "${{ inputs.what_if }}"
            RollbackToLastDeployment = $true
          }

          $templateParameterFile = "${{ inputs.parameter_file }}"
          If ($templateParameterFile) { $params['TemplateParameterFile'] = $templateParameterFile }

          $deploymentNameInput = "${{ inputs.deployment_name }}"
          $params['Name'] = If($deploymentNameInput) { $deploymentNameInput } Else { $(Get-Date).ToString("yyyyMMddHHss") }

          Write-Host "Running New-AzResourceGroupDeployment... $($params | Out-String)"
          $result = $(New-AzResourceGroupDeployment @params | ConvertTo-Json)

          Write-Host $result
          echo "::set-output name=deployment::$($result)"
        azPSVersion: "latest"
        failOnStandardError: "true"
